# Generated by Django 4.1 on 2022-09-03 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Metrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="TextGen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("input", models.TextField(null=True)),
                ("min_length", models.IntegerField(null=True)),
                ("max_length", models.IntegerField(null=True)),
                ("generation_text", models.TextField(null=True)),
                ("translated_text", models.TextField(null=True)),
                ("date", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("id",),
            },
        ),
        migrations.CreateModel(
            name="Translator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("input", models.TextField()),
                ("translated_text", models.TextField()),
                ("date", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("date",),
            },
        ),
    ]
