# Use postgres/example user/password credentials
version: '3.8'

services:

  postgres:
    container_name: postgres_chugunapp
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_NAME}
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - ${PG_PORT}:${PG_PORT}
    networks:
      - dockernet

  pgadmin:
    container_name: pgadmin_chugunapp
    image: dpage/pgadmin4:5.7
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - ./pgadmin:/var/lib/pgadmin
    user: root
    ports:
      - ${PGADMIN_PORT}:80
    networks:
      - dockernet

  redis:
    image: redis:7.2-alpine
    container_name: redis_chugunapp
    restart: always
    volumes:
      - redis_volume_data:/data
      - redis_conf:/etc/redis/redis.conf
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    env_file:
      - .env
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_DATABASES: ${REDIS_DATABASES}
    networks:
      - dockernet


  redis_insight:
    image: redislabs/redisinsight:latest
    container_name: redis_insight
    restart: always
    ports:
      - ${REDIS_INSIGHT_PORT}:${REDIS_INSIGHT_PORT}
    volumes:
      - redis_insight_volume_data:/db
    networks:
      - dockernet

  django:
    build:
      dockerfile:  Dockerfile
    container_name: django_chugunapp
    command: poetry run python manage.py runserver ${DJANGO_HOST}:${DJANGO_PORT}
    volumes:
      - ./:/usr/src/chugunapp
    ports:
      - ${DJANGO_PORT}:${DJANGO_PORT}
    env_file:
      - .env
    depends_on:
      - postgres
    networks:
      - dockernet



networks:
    dockernet:

volumes:
  redis_volume_data:
  redis_insight_volume_data:
  redis_conf:

